name: wunderbarai
description: "A Flutter project with provider-based theme switching."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  google_sign_in: ^6.2.2
  http: ^1.1.0
  intl: ^0.20.2
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  confetti: ^0.8.0
  record: ^6.2.0
  path_provider: ^2.1.5
  audioplayers: ^6.1.0
  flutter_markdown: ^0.7.7+1
  markdown: ^7.3.0
  firebase_ai:
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Bakery.png
    - lib/assets/RailwayStation.png
    - lib/assets/Restaurant.png
    - assets/test.mp3
