// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8D40ii0NvHNkkLB_r5DLYVZGNVnwv6VE',
    appId: '1:381763033963:web:4b81f28dc0d665dfed8a2e',
    messagingSenderId: '381763033963',
    projectId: 'language-buddy-a626a',
    authDomain: 'language-buddy-a626a.firebaseapp.com',
    storageBucket: 'language-buddy-a626a.firebasestorage.app',
    measurementId: 'G-GD2DLZMYSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJW9qL02gFtZEi6lMRoKLlR1PSXyk0BS4',
    appId: '1:381763033963:android:12b3ca0eecf2f62fed8a2e',
    messagingSenderId: '381763033963',
    projectId: 'language-buddy-a626a',
    storageBucket: 'language-buddy-a626a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ6hOhXGFQ9KTgRpo7j3hzvuxfy74N2R0',
    appId: '1:381763033963:ios:735cc6976121f743ed8a2e',
    messagingSenderId: '381763033963',
    projectId: 'language-buddy-a626a',
    storageBucket: 'language-buddy-a626a.firebasestorage.app',
    iosClientId: '381763033963-o5po8dv6eh785a6ti00ctvpmjfqdg62b.apps.googleusercontent.com',
    iosBundleId: 'com.example.wunderbarai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ6hOhXGFQ9KTgRpo7j3hzvuxfy74N2R0',
    appId: '1:381763033963:ios:735cc6976121f743ed8a2e',
    messagingSenderId: '381763033963',
    projectId: 'language-buddy-a626a',
    storageBucket: 'language-buddy-a626a.firebasestorage.app',
    iosClientId: '381763033963-o5po8dv6eh785a6ti00ctvpmjfqdg62b.apps.googleusercontent.com',
    iosBundleId: 'com.example.wunderbarai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8D40ii0NvHNkkLB_r5DLYVZGNVnwv6VE',
    appId: '1:381763033963:web:31d7953332ca8f7fed8a2e',
    messagingSenderId: '381763033963',
    projectId: 'language-buddy-a626a',
    authDomain: 'language-buddy-a626a.firebaseapp.com',
    storageBucket: 'language-buddy-a626a.firebasestorage.app',
    measurementId: 'G-6DEDG9GW5C',
  );
}
